# Generated by Django 3.1.7 on 2021-05-20 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='accounts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t_num', models.IntegerField()),
                ('num', models.IntegerField()),
                ('time', models.TimeField()),
                ('date', models.DateField()),
                ('cuisine', models.CharField(max_length=50)),
            ],
        ),
    ]
